### ISSUE TITLE
Allow language files to be divided or data to be nested

### ISSUE THREAD

**Issue by Emigre** [assemble/assemble-middleware-i18n#54]
I have a data file with translations for a language: `es.yml` (spanish in this case) and I'd like to divide it. 

Is it possible to split the translation for that language between several files?

If not, is it possible to nest key-value pairs inside the file?...
```yaml
index:
  text: Hola mundo!
  fruit: plátano
contact:
  text: Adiós mundo!
```
I've tried to use the helper as `{{i18n "index.text"}}` but it doesn't seem to work.

Apologies if any of those options is actually possible, I've had the impression that they are not.
