### ISSUE TITLE
arrays and front-matter variables

### ISSUE THREAD

**Issue by thedamon** [assemble/assemble-middleware-i18n#57]
I have this set up so that I can call strings with the i18n helper, but I need to figure out how to handle front-matter variables on a page, and iterating over arrays of data.

Is there a standard/assumed way of doing this?

I want to achieve something like the following:
```
en:
  title: Bananas
fr:
  title: Les bananes
---
{{title}}
```
This of course overwrites the en/fr variable so all the other keys are lost and the build fails. My assumption is I need to set these translations in the `i18n\en.yml` etc?

Then how do I handle, say, an array in my data using `{{each}}`? I can't pass a helper to a helper

```

fruits:
-
  name: apple
  color: red or green
  size: medium
-
  name: banana
  color: yellow
  size: medium
-
  name: blueberry
  color: blue
  size: small
```
```
{{#each fruits}}
  {{name}}
{{/each}}
```
Is the key to do `fruits: <%= i18n.fruits %>` in the front-matter?  that doesn't seem to be working...

**Comment by LaurentGoderre** [comment]
I think you need to do `fruits: <%= i18n[language].fruits %>`.

**Comment by eikawata** [comment]
That also does not work.

In my case, I have an array of objects stored in an external file as follows.

books.yml

```
books:
  - book:
      - title: Book Foo
      - description: foo foo
  - book:
      - title: Book Bar
      - description: bar bar
```

I want to do `{{#each}}` on the array inside Handlebars template, so I did

```
---
books: <%= i18n[language].books %>
---

{{#each books}}
  <h2>{{ book.title }}</h2>
  <p>{{ book.description }}</p>
{{/each}}
```

This #each helper just outputs an empty block, without even rendering `<h2>` or `<p>`. But I noticed that if I do `{{#each en.books }} ... {{/each}}` (without using YFM), it works fine. Isn't this a bug?

By the way, having to define a variable in YFM for each array I want to use is really cumbersome. It'd be nice if we could do something like just `i18n.books`.
